spring:
  application:
    name: reservation-tracker-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/reservation_tracker
    username: root
    password: root1234
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 610707857819-ibb1jua9e8b36gj1a6vcq1dogc9vuvhc.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: Google
            provider: google

        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

server:
  port: 8080